version: '0.5'
uuid: 34eff718-da8a-40fc-94fa-341ac3c7b1db
package:
  name: 5gtango-project-sample
  vendor: eu.5gtango
  version: '0.1'
  maintainer: Name, Company, Contact
  description: Some description about this sample
descriptor_extension: yml
files:
- path: osm_nsd.yml
  type: application/vnd.etsi.osm.nsd
  tags:
  - etsi.osm
- path: osm_vnfd0.yml
  type: application/vnd.etsi.osm.vnfd
  tags:
  - etsi.osm
- path: tango_nsd.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: tango_vnfd0.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
