version: '0.5'
package:
  name: 5gtango-project-sample
  vendor: eu.5gtango
  version: '0.1'
  maintainer: Name, Company, Contact
  description: Some description about this sample
descriptor_extension: yml
files:
- path: osm_nsd.yml
  type: application/vnd.etsi.osm.nsd
  tags:
  - etsi.osm
  testing_tags:
  - foo
  - bar
- path: osm_vnfd0.yml
  type: application/vnd.etsi.osm.vnfd
  tags:
  - etsi.osm
- path: tango_nsd.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
  testing_tags:
  - could_be_anything
- path: tango_vnfd0.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: tstd-example.yml
  type: application/vnd.5gtango.tstd
  tags:
  - eu.5gtango
- path: rpd-example.yml
  type: application/vnd.5gtango.rpd
  tags:
  - eu.5gtango
- path: slad-example.yml
  type: application/vnd.5gtango.slad
  tags:
  - eu.5gtango
